# Generated by Django 5.0 on 2026-09-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_is_reported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='is_reported',
            new_name='reported',
        ),
    ]
